<a href="https://colab.research.google.com/github/sunilsm7/numpy-demos/blob/main/NumPy_the_absolute_basics_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy: the absolute basics for beginners

In [1]:
import numpy as np

### How to create a basic array

This section covers `np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`, `dtype`

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
#  an array filled with 0’s
np.zeros(2)

array([0., 0.])

In [6]:
#  an array filled with 1’s
np.ones(2)

array([1., 1.])

In [10]:
# Create an empty array with 2 elements
np.empty(3)

array([0.75, 0.75, 0.  ])

In [11]:
# array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [13]:
# And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size
np.arange(2, 9, 2)

array([2, 4, 6, 8])

### Specifying your data type

`Default data type is floating point (np.float64`)

In [15]:
x = np.ones(2, dtype=np.int64)
print(x)

[1 1]


## Adding, removing, and sorting elements

covers `np.sort()`, `np.concatenate()`

In [17]:
# Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
# concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## How do you know the shape and size of an array?

covers `ndarray.ndim`, `ndarray.size`, `ndarray.shape`

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is `(2, 3)`.

In [23]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                    
                           [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [25]:
# To find the number of dimensions of the array
array_example.ndim

3

In [26]:
# To find the total number of elements in the array
array_example.size

24

In [27]:
 # to find the shape of your array
 array_example.shape

(3, 2, 4)

### Can you reshape an array

Yes!

Using `arr.reshape()` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [31]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [32]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


### How to convert a 1D array into a 2D array (how to add a new axis to an array)

This section covers `np.newaxis`, `np.expand_dims`.



In [ ]:
# Using np.newaxis will increase the dimensions of your array by one dimension when used once. 
# This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.


In [39]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [38]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape


[[1 2 3 4 5 6]]


(1, 6)

You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimensio

In [40]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [42]:
# Or, for a column vector, you can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims

In [43]:
 a = np.array([1, 2, 3, 4, 5, 6])
 a.shape

(6,)

In [44]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

### Indexing and slicing

In [50]:
data = np.array([1, 2, 3])
data[1]
data[:2]
data[:-1]
data[1:2]
data[-2:]

array([2, 3])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays

In [54]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


2