<a href="https://colab.research.google.com/github/sunilsm7/numpy-demos/blob/main/Numpy_demos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Examples

In [1]:
import numpy as np
import sys

## The Basics

In [2]:
a = np.array([1,2,3,4,5], dtype='int32')
print(a)

[1 2 3 4 5]


In [3]:
b = np.array([[1,2,3,4],[4,5,6,7]])
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [4]:
# Get Dimension
a.ndim

1

In [5]:
# Get Shape
b.shape

(2, 4)

In [6]:
# Get data Type
a.dtype

dtype('int32')

In [7]:
# Get Size
a.itemsize

4

In [8]:
# Get Total Size
a.nbytes

20

In [9]:
# Get number of elements
a.size

5

## Accessing/Changing specific elements, rows, columns, etc

In [10]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [11]:
# Get a specific element [r, c]
a[1,5]

13

In [12]:
# Get a specific row 
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [13]:
# Get a specific column
a[:,2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [15]:
# Change Element
a[1,5] = 20
print(a)
a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]



*3-d example

In [16]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

4

In [18]:
# replace - required same shape
b[:,1,:] = [[9,9],[8,8]]

In [19]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


## Initializing Different Types of Arrays

In [21]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
# All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [25]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [27]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.37571727, 0.54169475],
       [0.172148  , 0.80315414],
       [0.70143464, 0.38294895],
       [0.97761296, 0.50017422]])

In [30]:
# Random Integer values
np.random.randint(4,80, size=(3,3))

array([[54, 53, 70],
       [65, 70, 22],
       [50, 44, 73]])

In [31]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [40]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
# copy arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Mathematics

In [42]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [43]:
a+2

array([3, 4, 5, 6])

In [44]:
a-2

array([-1,  0,  1,  2])

In [45]:
a * 2

array([2, 4, 6, 8])

In [47]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [48]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [49]:
a ** 2

array([ 1,  4,  9, 16])

In [51]:
# Take the sin
np.cos(a)
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

### Linear Algebra

In [55]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [56]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

### Statistics

In [57]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [58]:
np.min(stats)

1

In [59]:
np.max(stats)

6

In [60]:
np.max(stats, axis=1)

array([3, 6])

In [61]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [63]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,3))
print(after)

[[1 2 3 4]
 [5 6 7 8]]


ValueError: ignored

In [64]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [65]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous