<a href="https://colab.research.google.com/github/sunilsm7/numpy-demos/blob/main/NumPy_the_absolute_basics_for_beginners.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy: the absolute basics for beginners

In [2]:
import numpy as np

### How to create a basic array

This section covers `np.array()`, `np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`, `dtype`

In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
#  an array filled with 0’s
np.zeros(2)

array([0., 0.])

In [6]:
#  an array filled with 1’s
np.ones(2)

array([1., 1.])

In [7]:
# Create an empty array with 2 elements
np.empty(3)

array([0.75, 0.75, 0.  ])

In [8]:
# array with a range of elements
np.arange(4)

array([0, 1, 2, 3])

In [9]:
# And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size
np.arange(2, 9, 2)

array([2, 4, 6, 8])

### Specifying your data type

`Default data type is floating point (np.float64`)

In [10]:
x = np.ones(2, dtype=np.int64)
print(x)

[1 1]


## Adding, removing, and sorting elements

covers `np.sort()`, `np.concatenate()`

In [11]:
# Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
# concatenate
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [13]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## How do you know the shape and size of an array?

covers `ndarray.ndim`, `ndarray.size`, `ndarray.shape`

`ndarray.ndim` will tell you the number of axes, or dimensions, of the array.

`ndarray.size` will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

`ndarray.shape` will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is `(2, 3)`.

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                    
                           [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                           [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [15]:
# To find the number of dimensions of the array
array_example.ndim

3

In [16]:
# To find the total number of elements in the array
array_example.size

24

In [17]:
 # to find the shape of your array
 array_example.shape

(3, 2, 4)

### Can you reshape an array

Yes!

Using `arr.reshape()` will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [18]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [19]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


### How to convert a 1D array into a 2D array (how to add a new axis to an array)

This section covers `np.newaxis`, `np.expand_dims`.



In [20]:
# Using np.newaxis will increase the dimensions of your array by one dimension when used once. 
# This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.


In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)
a.shape

[1 2 3 4 5 6]


(6,)

In [22]:
a2 = a[np.newaxis, :]
print(a2)
a2.shape


[[1 2 3 4 5 6]]


(1, 6)

You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimensio

In [23]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [24]:
# Or, for a column vector, you can insert an axis along the second dimension
col_vector = a[:, np.newaxis]
print(col_vector)
col_vector.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


(6, 1)

You can also expand an array by inserting a new axis at a specified position with np.expand_dims

In [25]:
 a = np.array([1, 2, 3, 4, 5, 6])
 a.shape

(6,)

In [26]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

### Indexing and slicing

In [27]:
data = np.array([1, 2, 3])
data[1]
data[:2]
data[:-1]
data[1:2]
data[-2:]

array([2, 3])

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays

In [28]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
print(a[a<5])
print(a[a>5])

[1 2 3 4]
[ 6  7  8  9 10 11 12]


### How to create an array from existing data

This section covers ```slicing and indexing, np.vstack(), np.hstack(), np.hsplit(), .view(), copy()```

In [30]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
print(a)
arr1=a[3:8]
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]
[4 5 6 7 8]


 stack two existing arrays, both vertically and horizontally

In [31]:
a1 = np.array([[1,1], [2,2]])
a2 = np.array([[3,3], [4,4]])
print(a1)
print(a2)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [32]:
# stack them vertically with vstack:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [33]:
# stack them horizontally with hstack
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

 split an array into several smaller arrays using `hsplit`

In [34]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [35]:
#  to split this array into three equally shape
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

### Basic array operations

This section covers addition, subtraction, multiplication, division, and more

In [36]:
# addition
data = np.array([1,2])
ones = np.ones(2, dtype='int')

print("data: ", data)
print("ones: ", ones)

result = data + ones
print("result: ", result)

data:  [1 2]
ones:  [1 1]
result:  [2 3]


In [37]:
# more than just addition
res_sub = data - ones
res_mul = data * ones
res_div = data / ones
print("sub: ", res_sub)
print("multi: ", res_mul)
print("div: ", res_div)

sub:  [0 1]
multi:  [1 2]
div:  [1. 2.]


In [38]:
# sum of elements
a = np.array([1, 2, 3, 4])
a.sum()

10

To add the rows or the columns in a 2D array, you would specify the axis.

In [39]:
b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)
b.sum(axis=1)

array([2, 4])

### Broadcasting

There are times when you might want to carry out an operation between an array and a single number (also called an operation between a vector and a scalar) or between arrays of two different sizes. For example, your array (we’ll call it “data”) might contain information about distance in miles but you want to convert the information to kilometers. You can perform this operation with

In [40]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

NumPy understands that the multiplication should happen with each cell. That concept is called broadcasting. Broadcasting is a mechanism that allows NumPy to perform operations on arrays of different shapes. The dimensions of your array must be compatible, for example, when the dimensions of both arrays are equal or when one of them is 1. If the dimensions are not compatible, you will get a ValueError

### More useful array operations

This section covers ```maximum, minimum, sum, mean, product, standard deviation, and more```



In [42]:
data = np.array([1.0, 2.0, 3.0])
data_max = data.max()
data_min = data.min()
data_sum = data.sum()
print('max ', data_max)
print('min ', data_min)
print('sum ', data_sum)

max  3.0
min  1.0
sum  6.0


### Creating matrices

You can pass Python lists of lists to create a 2-D array (or “matrix”) to represent them in NumPy.

In [43]:
data = np.array([[1, 2], [3, 4]])
data


array([[1, 2],
       [3, 4]])

Indexing and slicing operations are useful when you’re manipulating matrices:

In [47]:
data[0:1]

array([[1, 2]])

In [48]:
data[1:3]

array([[3, 4]])

In [49]:
data[0:2,0]

array([1, 3])

You can aggregate matrices the same way you aggregated vectors:

In [52]:
data.max()
data.min()
data.sum()

10

You can aggregate all the values in a matrix and you can aggregate them across columns or rows using the axis parameter:

In [53]:
data.max(axis=0)

array([3, 4])

In [54]:
data.max(axis=1)

array([2, 4])

### How to get unique items and counts

You can find the unique elements in an array easily with `np.unique`

In [57]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
print(a)

[11 11 12 13 14 15 16 17 12 13 11 14 18 19 20]


In [58]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


To get the indices of unique values in a NumPy array (an array of first index positions of unique values in the array), just pass the return_index argument in np.unique() as well as your array.

In [59]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


You can pass the return_counts argument in np.unique() along with your array to get the frequency count of unique values in a NumPy array

In [60]:
 unique_values, occurrence_count = np.unique(a, return_counts=True)
 print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


### Transposing and reshaping a matrix

transpose your array with `arr.transpose()`.

In [62]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [63]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

### How to reverse an array
NumPy’s `np.flip()` function allows you to flip, or reverse, the contents of an array along an axis. When using `np.flip`, specify the array you would like to reverse and the axis. If you don’t specify the axis, NumPy will reverse the contents along all of the axes of your input array.

#### Reversing a 1D array

In [65]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr)

reversed_arr = np.flip(arr)
print(reversed_arr)

[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]


#### Reversing a 2D array

In [67]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr_2d)

reversed_arr_2d = np.flip(arr_2d)
print(reversed_arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


### Reshaping and flattening multidimensional arrays
This section covers `.flatten()`,`ravel()`

There are two popular ways to flatten an array: `.flatten()` and `.ravel()`. The primary difference between the two is that the new array created using `ravel()` is actually a reference to the parent array (i.e., a “view”). This means that any changes to the new array will affect the parent array as well. Since `ravel` does not create a copy, it’s memory efficient.

In [69]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [70]:
# You can use flatten to flatten your array into a 1D array.
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [71]:
# When you use flatten, changes to your new array won’t change the parent array.
a1 = x.flatten()
a1[0] = 99
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


But when you use ravel, the changes you make to the new array will affect the parent array.

In [72]:
a2 = x.ravel()
print(a2)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [73]:
a2[0] = 98
print(x)

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
