<a href="https://colab.research.google.com/github/sunilsm7/numpy-demos/blob/main/Numpy_demos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Examples

In [5]:
import numpy as np
import sys

## The Basics

In [22]:
a = np.array([1,2,3,4,5], dtype='int32')
print(a)

[1 2 3 4 5]


In [8]:
b = np.array([[1,2,3,4],[4,5,6,7]])
print(b)

[[1 2 3 4]
 [4 5 6 7]]


In [23]:
# Get Dimension
a.ndim

1

In [19]:
# Get Shape
b.shape

(2, 4)

In [24]:
# Get data Type
a.dtype

dtype('int32')

In [25]:
# Get Size
a.itemsize

4

In [27]:
# Get Total Size
a.nbytes

20

In [28]:
# Get number of elements
a.size

5

## Accessing/Changing specific elements, rows, columns, etc